---
- name: Create AMI from running instance and terminate instance upon completion
  hosts: localhost
  vars_files:
    - ec2_variables.yml
  tasks:
    - name: Remove previous custom image (if it exists)
      ec2_ami:
        state: absent
        region: "{{ ec2.aws_region }}"
        image_id: "{{ ec2.custom_image_id }}"
      failed_when: false

    - name: Create AMI from temporary instance
      ec2_ami:
        name: "{{ ec2.image_name }}.{{ ansible_date_time.iso8601|replace(':', '-') }}"
        state: present
        region: "{{ ec2.aws_region }}"
        description: "{{ ec2.ami_description }}" 
        wait: yes
        instance_id: "{{ hostvars[groups[ami_builder.group][0]].ec2_id }}"
      register: ami_output

    - name: Copy the new image id to the ec2_variables file  
      lineinfile: 'dest=./ec2_variables.yml state=present regexp="^  custom_image_id" line="  custom_image_id: {{ ami_output.image_id }}                 # Dynamically updated when a new AMI is built using build-finish.yml. You can edit this manually too."'

    - name: Terminate temporary instance
      ec2:
        state: absent
        region: "{{ ec2.aws_region }}"
        instance_ids: "{{ hostvars[groups[ami_builder.group][0]].ec2_id }}"
