---
- name: stop master instance
  gather_facts: no
  hosts: localhost
  vars_files: 
   - ec2_variables.yml
  tasks:
   - ec2:
       state: 'stopped'
       region: "{{ ec2.aws_region }}"
       instance_ids: "{{ hostvars[item].ec2_id }}"
     with_items:  
      - "{{ groups[master.group]|default([]) }}"
